### ISSUE TITLE
Wrong action in edit hosts file page

### ISSUE THREAD

**Issue by mnirun** [t895/DNSNet#9]
**DNSNet version:** 1.0.14
**DNSNet APK Source:** F-Droid
**Device:** realme 5 Pro 
**OS:** Android 11

I've found wrong action combobox in "Edit hosts file" page

[Combobox label] -> [Actual action]
Deny -> Ignore
Allow -> Deny
Ignore -> Allow

**Comment by t895** [comment]
Oh! I'll patch that in a moment
Thanks for the report

**Comment by t895** [comment]
Fixed and will be in the next release
